# Generated by Django 4.2 on 2024-05-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('F', 'Free'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='F', max_length=1)),
                ('period', models.CharField(choices=[('M', 'monthly'), ('Q', 'quarterly'), ('A', 'annually')], default='M', max_length=1)),
            ],
        ),
    ]
