# Generated by Django 4.2 on 2024-05-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_options_alter_membership_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.AlterModelTable(
            name='membership',
            table=None,
        ),
    ]
