# Generated by Django 4.2 on 2024-05-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.vendee')),
                ('vendor', models.ManyToManyField(to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'SelectedVendors',
                'db_table': 'SelectedVendor',
            },
        ),
    ]
