# Generated by Django 4.2 on 2024-03-21 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_alter_purchaseorderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
