# Generated by Django 4.2 on 2024-03-21 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_remove_purchaseorderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='creator',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
