# Generated by Django 4.2 on 2024-05-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_is_verify_email_user_is_verify_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('F', 'Free'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='F', max_length=1)),
            ],
            options={
                'db_table': 'Membership',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='userauths.membership'),
        ),
    ]
