# Generated by Django 4.2 on 2024-05-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_profile_id_alter_profile_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.OneToOneField(default='F', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='userauths.membership'),
        ),
    ]
