# Generated by Django 4.2 on 2024-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_profile_id_alter_profile_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='F', max_length=1),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
