# Generated by Django 4.2 on 2024-05-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_membership_options_alter_membership_table'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
        migrations.DeleteModel(
            name='wallet',
        ),
    ]
