# Generated by Django 4.2 on 2024-03-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='profile',
        ),
    ]
