# Generated by Django 4.2 on 2024-03-22 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_cart_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
