# Generated by Django 4.2 on 2024-03-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_video_media_media'),
        ('purchase', '0006_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
